### ISSUE TITLE
Support for Crossover / Wine?

### ISSUE THREAD

**Issue by justinmoh** [ottercorp/FFXIVQuickLauncher#48]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

The `Setup.exe` wouldn't run with crossover/wine.

So far the only message returned is **"Installation has failed: Please re-run this installer as a normal user instead of "Run as Administrator"**.

For the record, run as "non-admin user" is a known limitation in wine. With all the situation mentioned, eventually leads to the result:
- wine does not support non-admin installation
- this installer doesn't support admin privilege installation

[xivonmac](https://github.com/marzent/XIV-on-Mac) has provided a launcher solution for mac user, perhaps we could make an adaption between **xivonmac** and the **sdo** (win-only) launcher.

### Version

Standard version (Windows, Lutris)

### Platform

Mac OS X

**Comment by Bluefissure** [comment]
The XIVLauncher is having problems with wine and there's no need for us to fix it because there's a native version XIVLauncher.Core in Linux & MacOS.

You can get it at https://flathub.org/apps/details/cn.ottercorp.xivlaunchercn (Linux) or https://file.bluefissure.com/FFXIV/Dalamud/xlcore/macos (MacOS).
